name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TREE_STRUCTURE_TS_PAT }}

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Generate new tag version
        uses: mathieudutour/github-tag-action@v6.1
        id: tag_version
        with:
          github_token: ${{ secrets.TREE_STRUCTURE_TS_PAT }}
          release_branches: main
          dry_run: true

      - name: Update package.json
        shell: pwsh
        env:
          TAG_NAME: ${{ steps.tag_version.outputs.new_tag }}
        run: |
          $env:RELEASE_VERSION = $env:TAG_NAME.replace('v', '')
          $content = Get-Content .\package.json
          $content = $content | foreach-object { $_ -replace '(?<prefix>^.+"version": ")(.+)(?<suffix>",)$', "`${prefix}$env:RELEASE_VERSION`${suffix}" } 
          $content | foreach-object { [System.Text.RegularExpressions.Regex]::Unescape($_) } | Out-File .\package.json -Force -Encoding ascii

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(package-json): :bookmark: Bumped package.json version to ${{ steps.tag_version.outputs.new_tag }}"
          commit_user_email: jdamaschke@visorian.com
          branch: main

      - name: Generate new tag version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TREE_STRUCTURE_TS_PAT }}
          release_branches: main
